package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/miruken-go/miruken/setup"
)

var (
	norecursFlag bool   // -norecurs
	stdoutFlag   bool   // -stdout
	outputFlag   string // -output [y.go]
	suffixFlag   string // -suffix [Context,Provider]
	testsFlag    bool   // -tests
	unexportFlag bool   // -unexported
)

func init() {
	flag.BoolVar(&norecursFlag, "norecurs", false, "skip sub-directories")
	flag.StringVar(&outputFlag, "output", "feature", "name of the generated .go file")
	flag.StringVar(&suffixFlag, "suffix", "", "suffix of types to emit or * for all")
	flag.BoolVar(&stdoutFlag, "stdout", false, "write to stdout")
	flag.BoolVar(&testsFlag, "tests", false, "generate test types")
	flag.BoolVar(&unexportFlag, "unexported", false, "include unexported names")
}

func main() {
	flag.Parse()

	outFile := strings.TrimSuffix(outputFlag, ".go")

	suffixes := []string{
		"Handler", "Provider", "Consumer", "Receiver",
		"Controller", "Manager", "Mapper", "Factory",
		"Filter", "Validator", "Integrity", "Service",
		"Policy", "Gateway", "Bootstrap",
	}

	if suffixFlag == "*" {
		suffixes = nil
	} else if strings.HasPrefix(suffixFlag, "+") {
		if suffixFlag != "+" {
			suffixes = append(suffixes, strings.Split(suffixFlag[1:], ",")...)
		}
	} else if suffixFlag != "" {
		suffixes = strings.Split(suffixFlag, ",")
	}

	dir := "."
	if len(flag.Args()) > 0 {
		dir = flag.Args()[0]
	}
	if err := parseDir(dir, false, outFile+".go", suffixes); err != nil {
		panic(err)
	}
	if testsFlag {
		if err := parseDir(dir, true, outFile+"_test.go", suffixes); err != nil {
			panic(err)
		}
	}
}

func parseDir(
	dir string,
	tests bool,
	outFile string,
	suffixes []string,
) (err error) {
	info, err := os.Stat(dir)
	if err != nil {
		panic(err)
	}
	if !info.IsDir() {
		panic("path is not a directory: " + dir)
	}

	var featureName string
	if tests {
		featureName = "TestFeature"
	} else {
		featureName = "Feature"
	}

	// Read directory entries
	entries, err := os.ReadDir(dir)
	if err != nil {
		panic(err)
	}

	// Parse all matching .go files
	fset := token.NewFileSet()
	files := make(map[string]*ast.File)
	var pkgName string

	for _, entry := range entries {
		name := entry.Name()

		// Skip if not a file
		if entry.IsDir() {
			continue
		}

		// Skip if not a .go file
		if filepath.Ext(name) != ".go" {
			continue
		}

		// Skip the output file itself
		if name == outFile {
			continue
		}

		// Filter based on test files
		if strings.HasSuffix(name, "_test.go") != tests {
			continue
		}

		// Parse the file
		filePath := filepath.Join(dir, name)
		f, err := parser.ParseFile(fset, filePath, nil, 0)
		if err != nil {
			panic(err)
		}

		if pkgName == "" {
			pkgName = f.Name.Name
		}
		files[name] = f
	}

	// If no files were parsed, return early
	if len(files) == 0 {
		// Still need to process subdirectories
		if !norecursFlag {
			for _, entry := range entries {
				if entry.IsDir() {
					if err := parseDir(filepath.Join(dir, entry.Name()),
						tests, outFile, suffixes); err != nil {
						return err
					}
				}
			}
		}
		return nil
	}

	var buf, typBuf bytes.Buffer

	// Types
	printTo(&typBuf, files, ast.Typ, "\t\t&%s{},\n", suffixes)
	if typBuf.Len() == 0 {
		// Still need to process subdirectories
		if !norecursFlag {
			for _, entry := range entries {
				if entry.IsDir() {
					if err := parseDir(filepath.Join(dir, entry.Name()),
						tests, outFile, suffixes); err != nil {
						return err
					}
				}
			}
		}
		return nil
	}

	//goland:noinspection GoPrintFunctions
	_, _ = fmt.Fprintln(&buf, "// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken; DO NOT EDIT.")
	_, _ = fmt.Fprintln(&buf)
	_, _ = fmt.Fprintln(&buf, "package", pkgName)
	_, _ = fmt.Fprintln(&buf, "")
	_, _ = fmt.Fprintf(&buf, "import %q\n", setupPkgPath)
	_, _ = fmt.Fprintln(&buf, "")

	// Feature
	_, _ = fmt.Fprintf(&buf, "var %s setup.Feature = setup.FeatureFunc(func(setup *setup.Builder) error {\n", featureName)
	_, _ = fmt.Fprintln(&buf, "\tsetup.Specs(")

	if _, err := io.Copy(&buf, &typBuf); err != nil {
		return err
	}

	_, _ = fmt.Fprintln(&buf, "\t)")
	_, _ = fmt.Fprintln(&buf, "\treturn nil")
	_, _ = fmt.Fprintln(&buf, "})")

	if stdoutFlag {
		if _, err := io.Copy(os.Stdout, &buf); err != nil {
			return err
		}
	} else {
		filename := filepath.Join(dir, outFile)
		newFileData := buf.Bytes()
		oldFileData, _ := os.ReadFile(filename)
		if !bytes.Equal(newFileData, oldFileData) {
			err = os.WriteFile(filename, newFileData, 0o660)
			if err != nil {
				panic(err)
			}
		}
	}

	if !norecursFlag {
		for _, entry := range entries {
			if entry.IsDir() {
				if err := parseDir(filepath.Join(dir, entry.Name()),
					tests, outFile, suffixes); err != nil {
					return err
				}
			}
		}
	}

	return nil
}

func printTo(
	w io.Writer,
	files map[string]*ast.File,
	kind ast.ObjKind,
	format string,
	suffixes []string,
) {
	var names []string
	for _, f := range files {
		for name, object := range f.Scope.Objects {
			if object.Kind == kind && (unexportFlag || ast.IsExported(name)) {
				if spec := object.Decl.(*ast.TypeSpec); spec != nil && spec.TypeParams == nil {
					if _, ok := spec.Type.(*ast.StructType); ok {
						if suffixes == nil {
							names = append(names, name)
						} else {
							for _, suffix := range suffixes {
								if strings.HasSuffix(name, suffix) {
									names = append(names, name)
									break
								}
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(names)
	for _, name := range names {
		_, _ = fmt.Fprintf(w, format, name)
	}
}

var setupPkgPath = reflect.TypeFor[setup.Builder]().PkgPath()
