// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken; DO NOT EDIT.

package test

import (
	"github.com/miruken-go/miruken/setup"
)

var TestFeature setup.Feature = setup.FeatureFunc(func(setup *setup.Builder) error {
	setup.Specs(
		&AbortFilter{},
		&AccountHandler{},
		&BadHandler{},
		&BarHandler{},
		&ComplexAsyncHandler{},
		&ComplexAsyncProvider{},
		&CountByTwoHandler{},
		&CounterHandler{},
		&DependencyHandler{},
		&DependencyResolverHandler{},
		&EmailHandler{},
		&ErrorAsyncHandler{},
		&EverythingHandler{},
		&EverythingImplicitHandler{},
		&EverythingSpecHandler{},
		&ExceptionFilter{},
		&FilteringHandler{},
		&FooHandler{},
		&FooOptionsHandler{},
		&FooProvider{},
		&InvalidHandler{},
		&InvalidProvider{},
		&KeyFactory{},
		&KeyProvider{},
		&ListProvider{},
		&LogFilter{},
		&MetadataHandler{},
		&MetadataInvalidHandler{},
		&MixedHandler{},
		&MultiHandler{},
		&MultiKeyFactory{},
		&MultiProvider{},
		&NoConstraintProvider{},
		&NullFilter{},
		&OpenProvider{},
		&PersonProvider{},
		&SimpleAsyncHandler{},
		&SimpleAsyncProvider{},
		&SingletonErrorHandler{},
		&SingletonHandler{},
		&SpecialFilteringHandler{},
		&SpecificationHandler{},
		&SpecificationProvider{},
		&UnmanagedHandler{},
	)
	return nil
})
