// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken_types; DO NOT EDIT.

package test

import "reflect"

var HandlerTestTypes = []reflect.Type{
	reflect.TypeOf((*AbortFilter)(nil)),
	reflect.TypeOf((*BadHandler)(nil)),
	reflect.TypeOf((*BarHandler)(nil)),
	reflect.TypeOf((*CounterHandler)(nil)),
	reflect.TypeOf((*DependencyHandler)(nil)),
	reflect.TypeOf((*DependencyResolverHandler)(nil)),
	reflect.TypeOf((*EntityMapper)(nil)),
	reflect.TypeOf((*EverythingHandler)(nil)),
	reflect.TypeOf((*EverythingImplicitHandler)(nil)),
	reflect.TypeOf((*EverythingSpecHandler)(nil)),
	reflect.TypeOf((*ExceptionFilter)(nil)),
	reflect.TypeOf((*FilteringHandler)(nil)),
	reflect.TypeOf((*FooHandler)(nil)),
	reflect.TypeOf((*FooOptionsHandler)(nil)),
	reflect.TypeOf((*FooProvider)(nil)),
	reflect.TypeOf((*FormatMapper)(nil)),
	reflect.TypeOf((*InvalidHandler)(nil)),
	reflect.TypeOf((*InvalidMapper)(nil)),
	reflect.TypeOf((*InvalidProvider)(nil)),
	reflect.TypeOf((*ListProvider)(nil)),
	reflect.TypeOf((*LogFilter)(nil)),
	reflect.TypeOf((*MultiHandler)(nil)),
	reflect.TypeOf((*MultiProvider)(nil)),
	reflect.TypeOf((*NullFilter)(nil)),
	reflect.TypeOf((*OpenMapper)(nil)),
	reflect.TypeOf((*OpenProvider)(nil)),
	reflect.TypeOf((*PersonProvider)(nil)),
	reflect.TypeOf((*RootedService)(nil)),
	reflect.TypeOf((*ScopedService)(nil)),
	reflect.TypeOf((*SingletonErrorHandler)(nil)),
	reflect.TypeOf((*SingletonHandler)(nil)),
	reflect.TypeOf((*SpecialFilteringHandler)(nil)),
	reflect.TypeOf((*SpecificationHandler)(nil)),
	reflect.TypeOf((*SpecificationProvider)(nil)),
}

