// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/mirukentypes; DO NOT EDIT.

package test

import "github.com/miruken-go/miruken"
import "reflect"

var mirukenTestTypes = []reflect.Type{
	miruken.TypeOf[*AbortFilter](),
	miruken.TypeOf[*BadHandler](),
	miruken.TypeOf[*BarHandler](),
	miruken.TypeOf[*CounterHandler](),
	miruken.TypeOf[*DependencyHandler](),
	miruken.TypeOf[*DependencyResolverHandler](),
	miruken.TypeOf[*EntityMapper](),
	miruken.TypeOf[*EverythingHandler](),
	miruken.TypeOf[*EverythingImplicitHandler](),
	miruken.TypeOf[*EverythingSpecHandler](),
	miruken.TypeOf[*ExceptionFilter](),
	miruken.TypeOf[*FilteringHandler](),
	miruken.TypeOf[*FooHandler](),
	miruken.TypeOf[*FooOptionsHandler](),
	miruken.TypeOf[*FooProvider](),
	miruken.TypeOf[*FormatMapper](),
	miruken.TypeOf[*InvalidHandler](),
	miruken.TypeOf[*InvalidMapper](),
	miruken.TypeOf[*InvalidProvider](),
	miruken.TypeOf[*ListProvider](),
	miruken.TypeOf[*LogFilter](),
	miruken.TypeOf[*MultiHandler](),
	miruken.TypeOf[*MultiProvider](),
	miruken.TypeOf[*NullFilter](),
	miruken.TypeOf[*OpenMapper](),
	miruken.TypeOf[*OpenProvider](),
	miruken.TypeOf[*OpenValidator](),
	miruken.TypeOf[*PersonProvider](),
	miruken.TypeOf[*PlayerMapper](),
	miruken.TypeOf[*PlayerValidator](),
	miruken.TypeOf[*RootedService](),
	miruken.TypeOf[*ScopedService](),
	miruken.TypeOf[*Service](),
	miruken.TypeOf[*SingletonErrorHandler](),
	miruken.TypeOf[*SingletonHandler](),
	miruken.TypeOf[*SpecialFilteringHandler](),
	miruken.TypeOf[*SpecificationHandler](),
	miruken.TypeOf[*SpecificationProvider](),
	miruken.TypeOf[*TeamHandler](),
	miruken.TypeOf[*TeamValidator](),
	miruken.TypeOf[*UnmanagedHandler](),
}

var WithTestHandlers = miruken.InstallerFunc(func(registration *miruken.Registration) {
	registration.AddHandlerTypes(mirukenTestTypes...)
})
