// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken; DO NOT EDIT.

package test

import "github.com/miruken-go/miruken"

var TestFeature = miruken.InstallFeature(func(setup *miruken.SetupBuilder) error {
	setup.RegisterHandlers(
		&AbortFilter{},
		&BadHandler{},
		&BarHandler{},
		&CountByTwoHandler{},
		&CounterHandler{},
		&DependencyHandler{},
		&DependencyResolverHandler{},
		&EntityMapper{},
		&EverythingHandler{},
		&EverythingImplicitHandler{},
		&EverythingSpecHandler{},
		&ExceptionFilter{},
		&FilteringHandler{},
		&FooHandler{},
		&FooOptionsHandler{},
		&FooProvider{},
		&FormatMapper{},
		&InvalidHandler{},
		&InvalidMapper{},
		&InvalidProvider{},
		&ListProvider{},
		&LogFilter{},
		&MixedHandler{},
		&MultiHandler{},
		&MultiProvider{},
		&NullFilter{},
		&OpenMapper{},
		&OpenProvider{},
		&OpenValidator{},
		&PersonProvider{},
		&PlayerMapper{},
		&PlayerValidator{},
		&RootedService{},
		&ScopedService{},
		&Service{},
		&SingletonErrorHandler{},
		&SingletonHandler{},
		&SpecialFilteringHandler{},
		&SpecificationHandler{},
		&SpecificationProvider{},
		&TeamHandler{},
		&TeamValidator{},
		&UnmanagedHandler{},
	)
	return nil
})
