// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken_types; DO NOT EDIT.

package miruken

import "reflect"

var HandlerTestTypes = []reflect.Type{
	reflect.TypeOf((*BarHandler)(nil)),
	reflect.TypeOf((*CounterHandler)(nil)),
	reflect.TypeOf((*DependencyHandler)(nil)),
	reflect.TypeOf((*DependencyResolverHandler)(nil)),
	reflect.TypeOf((*EverythingHandler)(nil)),
	reflect.TypeOf((*FooHandler)(nil)),
	reflect.TypeOf((*FooProvider)(nil)),
	reflect.TypeOf((*GenericProvider)(nil)),
	reflect.TypeOf((*InvalidHandler)(nil)),
	reflect.TypeOf((*InvalidProvider)(nil)),
	reflect.TypeOf((*ListProvider)(nil)),
	reflect.TypeOf((*MultiHandler)(nil)),
	reflect.TypeOf((*MultiProvider)(nil)),
	reflect.TypeOf((*SpecificationHandler)(nil)),
	reflect.TypeOf((*SpecificationProvider)(nil)),
}

