// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken_types; DO NOT EDIT.

package miruken

import "reflect"

var HandlerTestTypes = map[string]reflect.Type{
	"BarHandler": reflect.TypeOf((*BarHandler)(nil)).Elem(),
	"CounterHandler": reflect.TypeOf((*CounterHandler)(nil)).Elem(),
	"DependencyHandler": reflect.TypeOf((*DependencyHandler)(nil)).Elem(),
	"DependencyResolverHandler": reflect.TypeOf((*DependencyResolverHandler)(nil)).Elem(),
	"EverythingHandler": reflect.TypeOf((*EverythingHandler)(nil)).Elem(),
	"FooHandler": reflect.TypeOf((*FooHandler)(nil)).Elem(),
	"FooProvider": reflect.TypeOf((*FooProvider)(nil)).Elem(),
	"GenericProvider": reflect.TypeOf((*GenericProvider)(nil)).Elem(),
	"InvalidHandler": reflect.TypeOf((*InvalidHandler)(nil)).Elem(),
	"InvalidProvider": reflect.TypeOf((*InvalidProvider)(nil)).Elem(),
	"ListProvider": reflect.TypeOf((*ListProvider)(nil)).Elem(),
	"MultiHandler": reflect.TypeOf((*MultiHandler)(nil)).Elem(),
	"MultiProvider": reflect.TypeOf((*MultiProvider)(nil)).Elem(),
	"SpecificationHandler": reflect.TypeOf((*SpecificationHandler)(nil)).Elem(),
	"SpecificationProvider": reflect.TypeOf((*SpecificationProvider)(nil)).Elem(),
}

