// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken_types; DO NOT EDIT.

package miruken

import "reflect"

var HandlerTestTypes = []reflect.Type{
	reflect.TypeOf((*BarHandler)(nil)).Elem(),
	reflect.TypeOf((*CounterHandler)(nil)).Elem(),
	reflect.TypeOf((*DependencyHandler)(nil)).Elem(),
	reflect.TypeOf((*DependencyResolverHandler)(nil)).Elem(),
	reflect.TypeOf((*EverythingHandler)(nil)).Elem(),
	reflect.TypeOf((*FooHandler)(nil)).Elem(),
	reflect.TypeOf((*FooProvider)(nil)).Elem(),
	reflect.TypeOf((*GenericProvider)(nil)).Elem(),
	reflect.TypeOf((*InvalidHandler)(nil)).Elem(),
	reflect.TypeOf((*InvalidProvider)(nil)).Elem(),
	reflect.TypeOf((*ListProvider)(nil)).Elem(),
	reflect.TypeOf((*MultiHandler)(nil)).Elem(),
	reflect.TypeOf((*MultiProvider)(nil)).Elem(),
	reflect.TypeOf((*SpecificationHandler)(nil)).Elem(),
	reflect.TypeOf((*SpecificationProvider)(nil)).Elem(),
}

