// Code generated by https://github.com/Miruken-Go/miruken/tools/cmd/miruken; DO NOT EDIT.

package test

import "github.com/miruken-go/miruken"

var TestFeature miruken.Feature = miruken.FeatureFunc(func(setup *miruken.SetupBuilder) error {
	setup.Specs(
		&TeamApiConsumer{},
		&TeamApiHandler{},
	)
	return nil
})
