name: build miruken

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  containerized_job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/miruken-go/demo.microservice.build:1699298856
      env:
        ghToken:         ${{ secrets.WORKFLOW_GH_TOKEN }}
        GH_TOKEN:        ${{ secrets.WORKFLOW_GH_TOKEN }}
        repositoryPath:  ${{ github.workspace }}
        repository:      ${{ github.repository }}
        repositoryOwner: ${{ github.repository_owner }}
        ref:             ${{ github.event.client_payload.ref || github.ref }}
        
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        submodules: 'recursive'
    - working-directory: ./cicd
      run: | 
        npm ci
        npm run publish
